pool:
  vmImage: 'Ubuntu 16.04'
steps:
  - script: wget -qO- --retry-connrefused https://storage.googleapis.com/matlabimagesus/public/install.sh | sudo -E bash
  - script: git clone https://github.com/bids-standard/bids-examples
  - script: matlab -batch "addpath Mcode; bids_unittest.run_test_job"
  - task: PublishTestResults@2
    inputs:
      testResultsFiles: test-output/**/*.xml
  - task: PublishTestResults@2
    inputs:
      testResultsFiles: test-output/cobertura/coverage.xml
  
