version: 2
jobs:
  build:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - run: wget -qO- --retry-connrefused https://storage.googleapis.com/matlabimagesus/public/install.sh | sudo -E bash
      - run: matlab -batch "addpath Mcode; bids_unittest.run_test_job"
      - store_test_results:
          path: test-output/junit
